import { repositories } from "../libs/app/repository/index.js";
import config from '../config/config.js'

import {
  /*user*/
  authRegisterUsecase,
  verifyotpUsecase,
  resendOtpUsecase,
  addProfileUseCase,
  addProfilesecUseCase,
  experienceUsecase,
  getJobPostUsecase,
  browseJobpostUsecase,
  applynowUsecase,
  notificationUsecase,
  markasReaduseCase,
  userContractUsecase,
  ContractactionuseCase,
  acceptedContractuseCase,
  submitJobUsecase,
  findWorkUsecase,
  getclientInfoUsecase,
  alljobproposalsUsecase,
  viewjobproposalsUsecase,
  userinfoUsecase,
  edituserInfoUsecase,
  savejobUsecese,
  savedjobUseCase,
  unsavejobUsecese,
  disLikejobUsecase,
  LikejobUsecase,
  editproposalUsecase,
  
  /*client*/
  submittedContractusecase,
  clientAuthUsecase,
  browseUsersUsecase,
  jobSubmitUseCase,
  browseJobUsecase,
  browseJobPostsUseCase,
  browseJobProposalsUsecase,
  shortListJobProposalsUsecase,
  unshortListJobProposalsUsecase,
  archiveJobProposalsUsecase,
  unarchiveJobProposalsUsecase,
  declineJobProposalsUsecase,
  offerLetterUsecase,
  createContractuseCase,
  saveAddressUsecase,
  paymentUsecase,
  verifypaymentuseCase,
  browseContractsUseCase,
  paymentAfterUsecase,
  getContractUsecase,
  getuserInfoUsecase,
  
  /*login*/
  loginUsecase,
  forgotPasswordUseCase,
  forgotVerifyOtpUseCase,
  otpResendOtpuseCase,
  resetPasswordUsecase,
  refreshTokenuseCase,
  googleSinUpVerifyUsecase,
  googleLoginUseCase,
  gitHubUsecase,
  gitUserInfoUsecase,
  gitLoginUsecase,
  isUserprofileUseCase,

  /*admin*/
  adminAuthuseCase,
  registerUsecase,
  getUserDataUseCase,
  getClientDataUseCase,
  blockUserUseCase,
  unblockUserUseCase,
  blockclientUseCase,
  unblockclientUseCase,

  // chat
  createChatuseCase,
  getChatUsecase,
  findchatUsecase,
  getmessageUsecase,
  messageUsecase
} from "../libs/usecase/index.js";

const use_case = {
  /*user*/
  authRegisterUsecase,
  verifyotpUsecase,
  resendOtpUsecase,
  addProfileUseCase,
  addProfilesecUseCase,
  experienceUsecase,
  isUserprofileUseCase,
  getJobPostUsecase,
  browseJobpostUsecase,
  applynowUsecase,
  notificationUsecase,
  markasReaduseCase,
  userContractUsecase,
  ContractactionuseCase,
  acceptedContractuseCase,
  submitJobUsecase,
  findWorkUsecase,
  getclientInfoUsecase,
  alljobproposalsUsecase,
  viewjobproposalsUsecase,
  userinfoUsecase,
  edituserInfoUsecase,
  savejobUsecese,
  savedjobUseCase,
  unsavejobUsecese,
  disLikejobUsecase,
  LikejobUsecase,
  editproposalUsecase,
  
  /*client*/
  submittedContractusecase,
  clientAuthUsecase,
  browseUsersUsecase,
  jobSubmitUseCase,
  browseJobUsecase,
  browseJobPostsUseCase,
  browseJobProposalsUsecase,
  shortListJobProposalsUsecase,
  unshortListJobProposalsUsecase,
  archiveJobProposalsUsecase,
  unarchiveJobProposalsUsecase,
  declineJobProposalsUsecase,
  offerLetterUsecase,
  createContractuseCase,
  saveAddressUsecase,
  paymentUsecase,
  verifypaymentuseCase,
  browseContractsUseCase,
  paymentAfterUsecase,
  getContractUsecase,
  getuserInfoUsecase,



  /*login*/
  loginUsecase,
  forgotPasswordUseCase,
  forgotVerifyOtpUseCase,
  otpResendOtpuseCase,
  resetPasswordUsecase,
  refreshTokenuseCase,
  googleSinUpVerifyUsecase,
  googleLoginUseCase,
  gitHubUsecase,
  gitUserInfoUsecase,
  gitLoginUsecase,

  /*admin*/
  adminAuthuseCase,
  registerUsecase,
  getUserDataUseCase,
  getClientDataUseCase,
  blockUserUseCase,
  unblockUserUseCase,
  blockclientUseCase,
  unblockclientUseCase,

  // chat
  createChatuseCase,
  getChatUsecase,
  findchatUsecase,
  getmessageUsecase,
  messageUsecase
};

export default { use_case, repositories, config };
